import { Contributor } from "./type";

export const contributorsArray: Contributor[] = [
  {
    id: 1,
    name: "Taha Dostifam",
    nameFa: "طاها دوستی‌فام",
    title: "Creator",
    picture: "https://avatars.githubusercontent.com/tahadostifam",
    github: "https://github.com/tahadostifam",
    mastodon: "https://mastodon.social/@tahadostifam",
    daramet: "https://daramet.com/tahadostifam",
    telegram: "https://t.me/tahadostifam",
  },
  {
    id: 2,
    name: "Alisan",
    nameFa: "علیسان",
    title: "Contributor",
    picture: "https://avatars.githubusercontent.com/azcpcf",
    github: "https://github.com/azcpcf",
    daramet: "https://daramet.com/oogway",
    telegram: "https://t.me/azcpcf",
  },
  {
    id: 3,
    name: "MaxBase",
    nameFa: "مکس بیس",
    title: "Contributor",
    picture: "https://avatars.githubusercontent.com/u/2658040?v=4",
    github: "https://github.com/BaseMax",
    telegram: "https://t.me/MAX_BASE",
  },
  {
    id: 4,
    name: "Saeed Dayani",
    nameFa: "سعید دیانی",
    title: "Contributor",
    picture: "https://avatars.githubusercontent.com/talionsd",
    github: "https://github.com/talionsd",
    telegram: "https://t.me/talionsd",
  },
  {
    id: 5,
    name: "MrPi",
    nameFa: "مستر پی",
    title: "Contributor",
    picture: "https://avatars.githubusercontent.com/imMrPi",
    github: "https://github.com/imMrPi",
    telegram: "https://t.me/imMrPi",
  },
  {
    id: 6,
    name: "meshya",
    nameFa: "مشیا",
    title: "Contributor",
    picture: "https://avatars.githubusercontent.com/meshya",
    github: "https://github.com/meshya",
    mastodon: "https://mas.to/@meshya",
    daramet: "https://daramet.com/meshya",
    telegram: "https://t.me/meshyah",
  },
  {
    id: 7,
    name: "Mahdi Rahmani",
    nameFa: "مهدی رحمانی",
    title: "Contributor",
    picture: "https://avatars.githubusercontent.com/u/110809899?v=4",
    github: "https://github.com/MahdiRahmany",
    linkedin: "https://www.linkedin.com/in/mahdirahmany",
    email: "mahdirahmani.cm@gmail.com",
    telegram: "https://t.me/Mahdy_l",
  },
  {
    id: 8,
    name: "dallas",
    nameFa: "دالاس",
    title: "Contributor",
    picture: "https://avatars.githubusercontent.com/dll-as",
    github: "https://github.com/dll-as",
    telegram: "https://t.me/dll_as",
  },
  {
    id: 9,
    name: "CluvexStudio",
    nameFa: "کلاوکس",
    title: "Contributor",
    picture: "https://avatars.githubusercontent.com/CluvexStudio",
    github: "https://github.com/CluvexStudio",
    telegram: "https://t.me/CluvexStudio",
  },
];
